---
title: "Group Project Notes"
author: "Amanda Chiachi"
date: "3/31/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

For our project we will be presenting the package **"Janitor"**

# Install the Following Package

**install.packages("janitor")**

# Load Libraries
```{r, message=FALSE}
library(janitor)
library(tidyverse)
library(here)
library(kableExtra)
```


# Notes about Package
### The main functions are:

-  clean_names() # Shane
-  tabyl() # Shane 
-  remove_empty() # Amanda 
-  get_dupes() # Ruth 
-  excel_numeric_to_date() # Kevin 

#Cleaning Data
- How to use remove_empty  
```{r}
#first make a simple data frame 
a <- data.frame(v1 = c(7, 6, 4, 5),
                v2 = c(NA, NA, NA, NA),
                v3 = c("a", "b", "c", "d"), 
                v4 = c(6, 5, 8, 10))
a %>% #data frame name
  kbl()%>% #make a table in RMarkdown
  kable_classic() #classic theme

a_clean<-a %>% #rename data frame
  remove_empty(c("rows", "cols")) #checks for empty columns and rows, removes them!

a_clean%>%  #data frame name 
  kbl()%>% #make a table in RMarkdown
  kable_classic() #classic theme
```
# Usefullness on a real data set 
```{r}
coralgrowth<-read_csv(here("first_draft/data/CoralGrowth.csv")) #bring in the data
coralgrowth %>% # data frame name
  kbl() %>% # make a table in RMarkdown
  kable_classic() # classic theme

coralgrowth_clean<-coralgrowth%>%  #rename data set
  remove_empty(c("rows", "cols")) #remove any rows or columns with all NAs
coralgrowth_clean %>% # data frame name
  kbl()%>% #make a table in RMarkdown
  kable_classic() # classic theme 
```


